name: Build CI

on: [push, pull_request]

jobs:
  build:
    if: github.repository == 'ant-design/pro-components'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [24]
        os: [ubuntu-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build
        env:
          PRO_COMPONENTS_CI: CI
      - run: pnpm run lint
